# Generated by Django 6.0 on 2025-12-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_badges_and_avatar_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="badge",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="badges/"),
        ),
    ]
